services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"

volumes:
  postgres-data:
