services:
  postgres:
    image: postgres:13
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "${PGADMIN_DEFAULT_PORT}:80"

  mysql:
    image: mysql:5
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file:
      - .env
    environment:
      - PMA_HOST=mysql
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - mysql

volumes:
  postgres-data:
  mysql-data:
